-- 問1
INSERT INTO
	ITEMS (ID, CATEGORY_ID, NAME, PRICE)
VALUES
	(13, 1, '鰯', 150),
	(14, 2, '羊', 650);

-- 問2
UPDATE items SET price = price * 0.9;

-- 問3
DELETE FROM employees WHERE end_date <= '2013-03-31';

-- 問4
SELECT id, name, email, start_date, end_date FROM employees WHERE START_DATE = '2000-01-01';

-- 問5
SELECT regions.name, p.name FROM regions INNER JOIN prefectures as p ON p.region_code = regions.code;

-- 問6
SELECT
	SUM(POPULATIONS.POPULATION)
FROM
	POPULATIONS AS populations;

-- 問7
SELECT
	P.NAME AS PREFECTURE,
	G.NAME AS GENDER,
	SUM(POP.POPULATION) AS POPULATION
FROM
	POPULATIONS AS POP
	JOIN PREFECTURES AS P ON P.CODE = POP.PREFECTURE_CODE
	JOIN REGIONS AS R ON R.CODE = P.REGION_CODE
	JOIN GENDERS AS G ON G.CODE = POP.GENDER_CODE
WHERE
	R.CODE = '80'
GROUP BY
	P.NAME,
	POP.POPULATION,
	G.NAME,
	R.CODE
ORDER BY
	POP.POPULATION DESC,
	R.CODE DESC;
